spring:
  cloud:
    aws:
      parameterstore:
        enabled: true
  config:
    import[0]: "aws-parameterstore:/config/demo/prod/auth/"
    import[1]: "aws-parameterstore:/config/demo/prod/db/"
    import[2]: "aws-parameterstore:/config/demo/prod/security/"
    import[3]: "aws-parameterstore:/config/demo/prod/notification/"
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: WARN
    ExecutionTimeLogger: DEBUG
    io.awspring.cloud: DEBUG
