spring:
  main:
    allow-circular-references: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      naming:
        physical-strategy: com._2cha.demo.global.config.UppercaseNamingStrategy
    open-in-view: false
logging:
  level:
    com:
      _2cha:
        demo:
          DemoApplication: INFO
    RequestLogger: INFO