spring:
  cloud:
    aws:
      parameterstore:
        enabled: true
  config:
    import[0]: "aws-parameterstore:/config/demo/prod/auth/"
    import[1]: "aws-parameterstore:/config/demo/prod/db/"
    import[2]: "aws-parameterstore:/config/demo/prod/security/"
    import[3]: "aws-parameterstore:/config/demo/prod/notification/"
    import[4]: "aws-parameterstore:/config/demo/prod/storage/"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        search.backend:
          type: elasticsearch
          uris: ${ELASTICSEARCH_URI}  # ex: http://localhost:9200
          analysis.configurer: class:com._2cha.demo.recommendation.config.ElasticsearchAnalyzerConf