spring:
  main:
    allow-circular-references: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      naming:
        physical-strategy: com._2cha.demo.global.config.UppercaseNamingStrategy
    open-in-view: false
  data:
    web.pageable:
      page-parameter: page_number
      size-parameter: page_size
  autoconfigure:
    # https://github.com/hibernate/hibernate-search/pull/3199/commits/a06b2bac040c5fead412213bf67081d420067e0c
    # Spring Boot includes "auto-configuration" that triggers as soon as a dependency is detected in the classpath.
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration