spring:
  cloud:
    aws:
      parameterstore:
        enabled: true
  config:
    import[0]: "aws-parameterstore:/demo/config/prod/auth"
    import[1]: "aws-parameterstore:/demo/config/prod/db"
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com._2cha.demo.global.config.UppercaseNamingStrategy
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    root: WARN
    com:
      _2cha:
        demo:
          DemoApplication: INFO
          global.interceptor.LogInterceptor: INFO
    io.awspring.cloud: DEBUG
